//djRadios
export type djRadiosType = {
  id: number,
  picUrl: string,
  name: string,
  programCount: number,
  subCount: number,
  userId: number,
  nickname: string
};

export type radiosType = {
  "dj": {
    "defaultAvatar": boolean,
    "province": number,
    "authStatus": number,
    "followed": boolean,
    "avatarUrl": string,
    "accountStatus": number,
    "gender": number,
    "city": number,
    "birthday": number,
    "userId": number,
    "userType": number,
    "nickname": string,
    "signature": string,
    "description": string,
    "detailDescription": string,
    "avatarImgId": number,
    "backgroundImgId": number,
    "backgroundUrl": string,
    "authority": number,
    "mutual": boolean,
    "expertTags": null,
    "experts": null,
    "djStatus": number,
    "vipType": number,
    "remarkName": string | null,
    "avatarImgIdStr": string,
    "backgroundImgIdStr": string,
    "avatarImgId_str": string
  },
  "category": string,
  "buyed": boolean,
  "price": number,
  "originalPrice": number,
  "discountPrice": string | null,
  "purchaseCount": number,
  "lastProgramName": string,
  "videos": string | null,
  "finished": boolean,
  "underShelf": boolean,
  "liveInfo": string | null,
  "categoryId": number,
  "picId": number,
  "createTime": number,
  "lastProgramId": number,
  "feeScope": number,
  "subCount": number,
  "programCount": number,
  "lastProgramCreateTime": number,
  "radioFeeType": number,
  "picUrl": string,
  "desc": string,
  "name": string,
  "id": number,
  "rcmdtext": string
};

//cateList
export type categoriesType = {
  "pic96x96Url": string,
  "pic84x84IdUrl": string,
  "pic56x56Url": string,
  "pic96x96IdStr": string,
  "picPCWhiteStr": string,
  "picPCWhiteUrl": string,
  "picPCBlackStr": string,
  "picPCBlackUrl": string,
  "picWebStr": string,
  "picWebUrl": string,
  "picMacId": string,
  "picMacUrl": string,
  "picUWPId": string,
  "picUWPUrl": string,
  "picIPadStr": string,
  "picIPadUrl": string,
  "pic56x56IdStr": string,
  "pic56x56Id": number,
  "pic96x96Id": number,
  "picPCWhite": number,
  "picPCBlack": number,
  "picWeb": number,
  "picIPad": number,
  "pic84x84Id": number,
  "name": string,
  "id": number
};

//playlist
export type catListType = {
  "all": {
    "name": string,
    "resourceCount": number,
    "imgId": number,
    "imgUrl": string | null,
    "type": number,
    "category": number,
    "resourceType": number,
    "hot": string,
    "activity": string
  },
  "sub": Array<subType>,
  "categories": {
    "0": string,
    "1": string,
    "2": string,
    "3": string,
    "4": string
  }
};
export type subType = {
  "name": string,
  "resourceCount": number,
  "imgId": number,
  "imgUrl": string | null,
  "type": number,
  "category": number,
  "resourceType": number,
  "hot": boolean,
  "activity": boolean
};

export type playlistsType = {
  id: number,
  name: string,
  picUrl: string,
  nickname: string
};

export type TempPlaylistsType = {
  "name": string,
  "id": number,
  "trackNumberUpdateTime": number,
  "status": number,
  "userId": number,
  "createTime": number,
  "updateTime": number,
  "subscribedCount": number,
  "trackCount": number,
  "cloudTrackCount": number,
  "coverImgUrl": string,
  "coverImgId": number,
  "description": string,
  "tags": string[],
  "playCount": number,
  "trackUpdateTime": number,
  "specialType": number,
  "totalDuration": number,
  "creator": {
    "defaultAvatar": boolean,
    "province": number,
    "authStatus": number,
    "followed": false,
    "avatarUrl": string,
    "accountStatus": number,
    "gender": number,
    "city": number,
    "birthday": number,
    "userId": number,
    "userType": number,
    "nickname": string,
    "signature": string,
    "description": string,
    "detailDescription": string,
    "avatarImgId": number,
    "backgroundImgId": number,
    "backgroundUrl": string,
    "authority": number,
    "mutual": boolean,
    "expertTags": string[],
    "experts": string | null,
    "djStatus": number,
    "vipType": number,
    "remarkName": string | null,
    "backgroundImgIdStr": string,
    "avatarImgIdStr": string,
    "avatarImgId_str": string
  },
  "tracks": string | null,
  "subscribers": string[] | [],
  "subscribed": boolean,
  "commentThreadId": string,
  "newImported": boolean,
  "adType": number,
  "highQuality": boolean,
  "privacy": number,
  "ordered": boolean,
  "anonimous": boolean,
  "coverStatus": number,
  "recommendInfo": string | null,
  "shareCount": number,
  "coverImgId_str": string,
  "commentCount": number,
  "alg": string
};

//rank
export type rankType = {
  "program": {
    "mainSong": {
      "name": string,
      "id": number,
      "position": number,
      "alias": string[] | [],
      "status": number,
      "fee": number,
      "copyrightId": number,
      "disc": string,
      "no": number,
      "artists": [
        {
          "name": string,
          "id": number,
          "picId": number,
          "img1v1Id": number,
          "briefDesc": string,
          "picUrl": string,
          "img1v1Url": string,
          "albumSize": number,
          "alias": string[] | [],
          "trans": string,
          "musicSize": number,
          "topicPerson": number
        }
      ],
      "album": {
        "name": string,
        "id": number,
        "type": string | null,
        "size": number,
        "picId": number,
        "blurPicUrl": string,
        "companyId": number,
        "pic": number,
        "picUrl": string,
        "publishTime": number,
        "description": string,
        "tags": string,
        "company": string | null,
        "briefDesc": string,
        "artist": {
          "name": string,
          "id": number,
          "picId": number,
          "img1v1Id": number,
          "briefDesc": string,
          "picUrl": string,
          "img1v1Url": string,
          "albumSize": number,
          "alias": [],
          "trans": "",
          "musicSize": number,
          "topicPerson": number
        },
        "songs": [],
        "alias": [],
        "status": number,
        "copyrightId": number,
        "commentThreadId": string,
        "artists": [
          {
            "name": string,
            "id": 0,
            "picId": 0,
            "img1v1Id": 0,
            "briefDesc": string,
            "picUrl": string,
            "img1v1Url": string,
            "albumSize": 0,
            "alias": [],
            "trans": string,
            "musicSize": 0,
            "topicPerson": 0
          }
        ],
        "subType": string | null,
        "transName": string | null,
        "mark": 0,
        "picId_str": string
      },
      "starred": false,
      "popularity": 5,
      "score": 5,
      "starredNum": 0,
      "duration": 205035,
      "playedNum": 0,
      "dayPlays": 0,
      "hearTime": 0,
      "ringtone": string | null,
      "crbt": string | null,
      "audition": string | null,
      "copyFrom": string,
      "commentThreadId": string,
      "rtUrl": string | null,
      "ftype": 0,
      "rtUrls": [],
      "copyright": 1,
      "transName": string | null,
      "sign": string | null,
      "mark": 0,
      "noCopyrightRcmd": string | null,
      "rtype": 0,
      "rurl": string | null,
      "mvid": 0,
      "bMusic": {
        "name": string,
        "id": 3416371860,
        "size": 3281023,
        "extension": string,
        "sr": 44100,
        "dfsId": 0,
        "bitrate": 128000,
        "playTime": 205035,
        "volumeDelta": 0
      },
      "mp3Url": string | null,
      "hMusic": {
        "name": string,
        "id": 3416371858,
        "size": 8202493,
        "extension": string,
        "sr": 44100,
        "dfsId": 0,
        "bitrate": 320000,
        "playTime": 205035,
        "volumeDelta": 0
      },
      "mMusic": {
        "name": string,
        "id": 3416371859,
        "size": 4921513,
        "extension": string,
        "sr": 44100,
        "dfsId": 0,
        "bitrate": 192000,
        "playTime": 205035,
        "volumeDelta": 0
      },
      "lMusic": {
        "name": string,
        "id": 3416371860,
        "size": 3281023,
        "extension": string,
        "sr": 44100,
        "dfsId": 0,
        "bitrate": 128000,
        "playTime": 205035,
        "volumeDelta": 0
      }
    },
    "songs": string | null,
    "dj": {
      "defaultAvatar": false,
      "province": 1000000,
      "authStatus": 0,
      "followed": false,
      "avatarUrl": string,
      "accountStatus": 0,
      "gender": 1,
      "city": 1010000,
      "birthday": -2209017600000,
      "userId": 496514385,
      "userType": 0,
      "nickname": string,
      "signature": string,
      "description": string,
      "detailDescription": string,
      "avatarImgId": 109951164540424080,
      "backgroundImgId": 109951164958856260,
      "backgroundUrl": string,
      "authority": 0,
      "mutual": false,
      "expertTags": string | null,
      "experts": string | null,
      "djStatus": 10,
      "vipType": 0,
      "remarkName": string | null,
      "avatarImgIdStr": string,
      "backgroundImgIdStr": string,
      "avatarImgId_str": string,
      "brand": string
    },
    "blurCoverUrl": string,
    "radio": {
      "dj": string | null,
      "category": string,
      "buyed": false,
      "price": 0,
      "originalPrice": 0,
      "discountPrice": string | null,
      "purchaseCount": number,
      "lastProgramName": string | null,
      "videos": string | null,
      "finished": false,
      "underShelf": false,
      "liveInfo": string | null,
      "picUrl": string,
      "lastProgramCreateTime": number,
      "lastProgramId": number,
      "desc": string,
      "categoryId": number,
      "picId": number,
      "createTime": number,
      "feeScope": number,
      "programCount": 2,
      "subCount": number,
      "radioFeeType": number,
      "name": string,
      "id": number,
      "subed": boolean
    },
    "duration": number,
    "buyed": boolean,
    "programDesc": string | null,
    "h5Links": string | null,
    "canReward": boolean,
    "auditStatus": number,
    "videoInfo": string | null,
    "score": number,
    "liveInfo": string | null,
    "alg": string | null,
    "programFeeType": number,
    "mainTrackId": number,
    "titbits": string | null,
    "trackCount": number,
    "titbitImages": string | null,
    "isPublish": true,
    "commentThreadId": string,
    "coverUrl": string,
    "serialNum": number,
    "smallLanguageAuditStatus": number,
    "reward": boolean,
    "description": string,
    "createTime": number,
    "channels": string[] | [],
    "listenerCount": number,
    "subscribedCount": number,
    "feeScope": number,
    "pubStatus": number,
    "bdAuditStatus": number,
    "name": string,
    "id": number,
    "subscribed": boolean,
    "shareCount": number,
    "likedCount": number,
    "commentCount": number
  },
  "rank": number
  "lastRank": number,
  "score": number,
  "programFeeType": number
};